//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiMTModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class veterinarTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veterinarTbl()
        {
            this.UsersTbl = new HashSet<UsersTbl>();
        }
    
        public int VeterinarId { get; set; }
        public string VeterinarName { get; set; }
        public string VeterinarEmail { get; set; }
        public string VeterinarAddress { get; set; }
        public string VeterinarCity { get; set; }
        public string VeterinarPhone1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersTbl> UsersTbl { get; set; }
    }
}
